name: Deny

on:
  push:
    branches: [main]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
      - ".github/workflows/deny.yml"
  pull_request:
    branches: [main]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
      - ".github/workflows/deny.yml"
  schedule:
    - cron: "47 6 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deny:
    name: cargo-deny (${{ matrix.checks }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        checks:
          - bans licenses sources
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: EmbarkStudios/cargo-deny-action@91bf2b620e09e18d6eb78b92e7861937469acedb # v2
        with:
          command: check ${{ matrix.checks }}
          arg: --hide-inclusion-graph
