name: Deny

on:
  push:
    branches: [main]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
      - ".github/workflows/deny.yml"
  pull_request:
    branches: [main]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "deny.toml"
      - ".github/workflows/deny.yml"
  schedule:
    - cron: "47 6 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deny:
    name: cargo-deny (${{ matrix.checks }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        checks:
          - bans licenses sources
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: EmbarkStudios/cargo-deny-action@a531616d8ce3b9177443e48a1159bc945a099823 # v2
        with:
          command: check ${{ matrix.checks }}
          arg: --hide-inclusion-graph
